# SETTINGS

In [12]:
import pandas as pd
import emoji
from datetime import datetime
import numpy as np
import os

# CONFIGURATION

In [13]:
# CSV Settings
project_dir = r"C:\cache\Youtube-ETL_Project"
raw_dir = os.path.join(project_dir, "data", "raw")
latest_raw_path = os.path.join(raw_dir, "latest_raw_path.txt")

if os.path.exists(latest_raw_path):
    with open(latest_raw_path, "r", encoding="utf-8") as f:
        csv_files = f.read().strip()
else:
    raw_files = [
        os.path.join(raw_dir, file_name)
        for file_name in os.listdir(raw_dir)
        if file_name.startswith("raw_youtube_") and file_name.endswith(".csv")
    ]
    if not raw_files:
        raise FileNotFoundError(f"No raw CSV files found in: {raw_dir}")
    csv_files = max(raw_files, key=os.path.getmtime)

if not os.path.exists(csv_files):
    raise FileNotFoundError(f"Raw CSV not found: {csv_files}")

raw_file_name = os.path.basename(csv_files)
cleaned_file_name = raw_file_name.replace("raw_youtube_", "cleaned_youtube_", 1)

print("CSV file to process:", csv_files)

CSV file to process: c:\cache\Youtube-ETL_Project\data\raw\raw_youtube_Jun_2026.csv

# READ CSV

In [ ]:
try:
    df = pd.read_csv(csv_files)
    print(f"Successfully read CSV files: {csv_files}, shape = {df.shape}")
    display(df.head(100))
except Exception as e:
    print(f"Error reading CSV files: {e}")
    raise

Successfully read CSV files: c:\cache\Youtube-ETL_Project\data\raw\raw_youtube_Jun_2026.csv, shape = (100, 16)

,video_id,video_title,channel_id,channel_name,subscriber_count,publish_date,video_url,duration,view_count,like_count,comment_count,tags,category,thumbnail_url,keyword,collection_date
0,GzNMN7Ijd8k,How to Earn ₹1 Lakh Per Month ??@PWEarnersPC,UCiGyWN6DEbnj2alu7iapuKQ,Physics Wallah - Alakh Pandey,14300000,2026-06-07T15:19:19Z,https://www.youtube.com/watch?v=GzNMN7Ijd8k,00:54:21,1489776,60814,5161,NaN,Education,https://i.ytimg.com/vi/GzNMN7Ijd8k/hqdefault.jpg,data analyst,2026-08-11
1,68FcZUpgC7w,AI Engineer Full Course | 16+ Hours | Beginne...,UCxZC-5v-UccF6FXGI7VXgoQ,The iScale,349000,2026-06-30T12:35:43Z,https://www.youtube.com/watch?v=68FcZUpgC7w,16:04:15,312651,14622,919,AI Engineer Full Course|AI Engineer|AI Course|...,Education,https://i.ytimg.com/vi/68FcZUpgC7w/hqdefault.jpg,data analyst,2026-08-11
2,X_IQ41y9jbg,Orientation Session 🔥 || Earners LAPTOP - Vide...,UCDkox5NLaLtrYssKumtfzNA,Earners LAPTOP,57100,2026-06-18T13:44:33Z,https://www.youtube.com/watch?v=X_IQ41y9jbg,00:44:45,182943,4658,960,NaN,People & Blogs,https://i.ytimg.com/vi/X_IQ41y9jbg/hqdefault.jpg,data analyst,2026-08-11
3,MOzEvNYvbik,Data Analyst Bootcamp (FREE 35+ Hour Full Cour...,UCLLw7jmFsvfIVaUFsLs8mlQ,Luke Barousse,661000,2026-06-02T12:00:29Z,https://www.youtube.com/watch?v=MOzEvNYvbik,35:37:05,153919,6906,479,NaN,Howto & Style,https://i.ytimg.com/vi/MOzEvNYvbik/hqdefault.jpg,data analyst,2026-08-11
4,ol9_NnC9-cc,Data Engineer Bootcamp (FREE 27+ Hour Course) ...,UCLLw7jmFsvfIVaUFsLs8mlQ,Luke Barousse,661000,2026-06-15T12:00:33Z,https://www.youtube.com/watch?v=ol9_NnC9-cc,27:19:55,110471,4952,260,NaN,Howto & Style,https://i.ytimg.com/vi/ol9_NnC9-cc/hqdefault.jpg,data analyst,2026-08-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,8F6_qiLZ_PY,Data Analyst Work From Home Job | 120 Days Tra...,UC2bEjcsQOaB49lak70vkzDQ,karrarhussainfreejobs,8270,2026-06-02T09:12:10Z,https://www.youtube.com/watch?v=8F6_qiLZ_PY,00:01:10,2846,22,5,NaN,Education,https://i.ytimg.com/vi/8F6_qiLZ_PY/hqdefault.jpg,data analyst,2026-08-11
96,xXPCo1H3y90,عقلية محلل البيانات + تطبيقات | Data Analyst M...,UCITfscBBm40O9MgtqiQC00w,Mustafa Othman,171000,2026-06-21T22:00:06Z,https://www.youtube.com/watch?v=xXPCo1H3y90,00:48:28,2761,153,13,NaN,Education,https://i.ytimg.com/vi/xXPCo1H3y90/hqdefault.jpg,data analyst,2026-08-11
97,fCYpr2askjU,Top 10 Data Analyst Jobs for Freshers 2026 | J...,UCVKyjXbEKdU1yj35hlUvKPQ,Jobsearchguru4u,15800,2026-06-27T08:21:24Z,https://www.youtube.com/watch?v=fCYpr2askjU,00:16:58,2687,93,24,data analyst jobs for fresher|data analyst job...,Education,https://i.ytimg.com/vi/fCYpr2askjU/hqdefault.jpg,data analyst,2026-08-11
98,Xqb1LQ54yXE,MIS Executive & Data Analyst Work Based on Inv...,UC6AoSktg5WGLME4mPqVc_bA,Abhijeetji Technical 4M,182000,2026-06-18T14:23:53Z,https://www.youtube.com/watch?v=Xqb1LQ54yXE,00:17:09,2635,85,9,mis executive work|data analyst work on real w...,People & Blogs,https://i.ytimg.com/vi/Xqb1LQ54yXE/hqdefault.jpg,data analyst,2026-08-11
99,4r9Wklh5syo,The Exact Path From Zero to $100K in Data Anal...,UCRsjR0vJxD0ufV90B9WX8lA,Kedeisha Bryan - Your Data Career Coach,49300,2026-06-25T17:39:20Z,https://www.youtube.com/watch?v=4r9Wklh5syo,00:12:34,2582,176,9,data analyst|data analytics|data analyst roadm...,Education,https://i.ytimg.com/vi/4r9Wklh5syo/hqdefault.jpg,data analyst,2026-08-11

# DATA FIGURE

In [15]:
# Overview of the DataFrame
print("Shape:", df.shape)
print("\n--- Dtypes ---")
print(df.dtypes)
print("\n--- Info ---")
df.info()

Shape: (100, 16)

--- Dtypes ---
video_id              str
video_title           str
channel_id            str
channel_name          str
subscriber_count    int64
publish_date          str
video_url             str
duration              str
view_count          int64
like_count          int64
comment_count       int64
tags                  str
category              str
thumbnail_url         str
keyword               str
collection_date       str
dtype: object

--- Info ---
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   video_id          100 non-null    str
 1   video_title       100 non-null    str
 2   channel_id        100 non-null    str
 3   channel_name      100 non-null    str
 4   subscriber_count  100 non-null    int64
 5   publish_date      100 non-null    str
 6   video_url         100 non-null    str
 7   duration          100 non-null    str
 8   view_count        100 non-null    int64
 9   like_count        100 non-null    int64
 10  comment_count     100 non-null    int64
 11  tags              86 non-null     str
 12  category          100 non-null    str
 13  thumbnail_url     100 non-null    str
 14  keyword           100 non-null    str
 15  collection_date   100 non-null    str
dtypes: int64(4), str(12)
memory usage: 12.6 KB

In [16]:
# 
numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns.tolist()
print("Các cột số:", numeric_cols)
display(df[numeric_cols].describe())

Các cột số: ['subscriber_count', 'view_count', 'like_count', 'comment_count']

       subscriber_count    view_count    like_count  comment_count
count      1.000000e+02  1.000000e+02    100.000000     100.000000
mean       9.189806e+05  3.944235e+04   1429.200000     141.760000
std        2.772846e+06  1.523914e+05   6249.342627     533.495697
min        1.660000e+02  2.582000e+03      0.000000       0.000000
25%        1.117500e+04  4.887750e+03    153.000000      10.000000
50%        5.710000e+04  1.069350e+04    319.500000      29.000000
75%        2.680000e+05  2.788425e+04    848.250000      92.000000
max        1.430000e+07  1.489776e+06  60814.000000    5161.000000

In [17]:
# Data Pivot Table - Viewcount by Video ID and Category
df.pivot_table(index='video_title', columns='category', values='view_count', aggfunc=np.sum, fill_value=0)

category,Autos & Vehicles,Education,Entertainment,Howto & Style,People & Blogs,Science & Technology,Sports
video_title,,,,,,,
#1 Certificate To Be an AI Engineer / Data Engineer / Data Analyst,0,79676,0,0,0,0,0
100% job in Data Analytics Easy NON IT Job,0,3960,0,0,0,0,0
"2 superset mass hiring | 3 Data Analyst (WFH), Amazon, IBM, Cisco and other 7 companies hirings",0,0,0,0,4185,0,0
"2026 FREE Data Analyst Bootcamp [23+ Hours] | SQL, Python, Pandas, Power BI, DAX & Real Projects",0,26184,0,0,0,0,0
3 Reasons You SHOULD NOT Become a Data Analyst! (Harsh Reality),0,5502,0,0,0,0,0
...,...,...,...,...,...,...,...
عقلية محلل البيانات + تطبيقات | Data Analyst Mindset + Case-studies,0,2761,0,0,0,0,0
"ఇంటి నుండే ₹28,000 ఉద్యోగం | Peroptyx Data Analyst Job వివరాలు మరియు ఎగ్జామ్ టిప్స్ | Nanda Voice",0,0,0,0,5099,0,0
🔴Data Analyst Internship out | For june 2026 | Work from Home | Stipend + Certificate 🔥,0,0,0,0,7266,0,0
🔴Report Making - Part time Work from Home job | Open for all | Data Analyst | Apply Now 🔥,0,71682,0,0,0,0,0
🚨 AI Taking Away Data Analyst Jobs! | The Truth You Need to Know!,0,10507,0,0,0,0,0

In [18]:
df.groupby("channel_name")["subscriber_count"].count().sort_values(ascending=False).head(10)

channel_name
Data Logic With Shivam        7
Skillcure Academy             5
Earners LAPTOP                3
Mansi G.                      3
Intellipaat                   3
Tricky Man                    3
WsCube Tech                   2
Top VarSity                   2
Unfiltered data analytics     2
Vimlesh - NIT'A               2
Name: subscriber_count, dtype: int64

# CLEANING DATA

In [19]:
# Video title and tags cleaning emoji
df["video_title"] = df["video_title"].fillna("").apply(lambda x: emoji.replace_emoji(x, replace="").strip())
df["tags"] = df["tags"].fillna("").apply(lambda x: emoji.replace_emoji(x, replace="").strip())
df

,video_id,video_title,channel_id,channel_name,subscriber_count,publish_date,video_url,duration,view_count,like_count,comment_count,tags,category,thumbnail_url,keyword,collection_date
0,GzNMN7Ijd8k,How to Earn ₹1 Lakh Per Month ??@PWEarnersPC,UCiGyWN6DEbnj2alu7iapuKQ,Physics Wallah - Alakh Pandey,14300000,2026-06-07T15:19:19Z,https://www.youtube.com/watch?v=GzNMN7Ijd8k,00:54:21,1489776,60814,5161,,Education,https://i.ytimg.com/vi/GzNMN7Ijd8k/hqdefault.jpg,data analyst,2026-08-11
1,68FcZUpgC7w,AI Engineer Full Course | 16+ Hours | Beginne...,UCxZC-5v-UccF6FXGI7VXgoQ,The iScale,349000,2026-06-30T12:35:43Z,https://www.youtube.com/watch?v=68FcZUpgC7w,16:04:15,312651,14622,919,AI Engineer Full Course|AI Engineer|AI Course|...,Education,https://i.ytimg.com/vi/68FcZUpgC7w/hqdefault.jpg,data analyst,2026-08-11
2,X_IQ41y9jbg,Orientation Session || Earners LAPTOP - Video...,UCDkox5NLaLtrYssKumtfzNA,Earners LAPTOP,57100,2026-06-18T13:44:33Z,https://www.youtube.com/watch?v=X_IQ41y9jbg,00:44:45,182943,4658,960,,People & Blogs,https://i.ytimg.com/vi/X_IQ41y9jbg/hqdefault.jpg,data analyst,2026-08-11
3,MOzEvNYvbik,Data Analyst Bootcamp (FREE 35+ Hour Full Cour...,UCLLw7jmFsvfIVaUFsLs8mlQ,Luke Barousse,661000,2026-06-02T12:00:29Z,https://www.youtube.com/watch?v=MOzEvNYvbik,35:37:05,153919,6906,479,,Howto & Style,https://i.ytimg.com/vi/MOzEvNYvbik/hqdefault.jpg,data analyst,2026-08-11
4,ol9_NnC9-cc,Data Engineer Bootcamp (FREE 27+ Hour Course) ...,UCLLw7jmFsvfIVaUFsLs8mlQ,Luke Barousse,661000,2026-06-15T12:00:33Z,https://www.youtube.com/watch?v=ol9_NnC9-cc,27:19:55,110471,4952,260,,Howto & Style,https://i.ytimg.com/vi/ol9_NnC9-cc/hqdefault.jpg,data analyst,2026-08-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,8F6_qiLZ_PY,Data Analyst Work From Home Job | 120 Days Tra...,UC2bEjcsQOaB49lak70vkzDQ,karrarhussainfreejobs,8270,2026-06-02T09:12:10Z,https://www.youtube.com/watch?v=8F6_qiLZ_PY,00:01:10,2846,22,5,,Education,https://i.ytimg.com/vi/8F6_qiLZ_PY/hqdefault.jpg,data analyst,2026-08-11
96,xXPCo1H3y90,عقلية محلل البيانات + تطبيقات | Data Analyst M...,UCITfscBBm40O9MgtqiQC00w,Mustafa Othman,171000,2026-06-21T22:00:06Z,https://www.youtube.com/watch?v=xXPCo1H3y90,00:48:28,2761,153,13,,Education,https://i.ytimg.com/vi/xXPCo1H3y90/hqdefault.jpg,data analyst,2026-08-11
97,fCYpr2askjU,Top 10 Data Analyst Jobs for Freshers 2026 | J...,UCVKyjXbEKdU1yj35hlUvKPQ,Jobsearchguru4u,15800,2026-06-27T08:21:24Z,https://www.youtube.com/watch?v=fCYpr2askjU,00:16:58,2687,93,24,data analyst jobs for fresher|data analyst job...,Education,https://i.ytimg.com/vi/fCYpr2askjU/hqdefault.jpg,data analyst,2026-08-11
98,Xqb1LQ54yXE,MIS Executive & Data Analyst Work Based on Inv...,UC6AoSktg5WGLME4mPqVc_bA,Abhijeetji Technical 4M,182000,2026-06-18T14:23:53Z,https://www.youtube.com/watch?v=Xqb1LQ54yXE,00:17:09,2635,85,9,mis executive work|data analyst work on real w...,People & Blogs,https://i.ytimg.com/vi/Xqb1LQ54yXE/hqdefault.jpg,data analyst,2026-08-11
99,4r9Wklh5syo,The Exact Path From Zero to $100K in Data Anal...,UCRsjR0vJxD0ufV90B9WX8lA,Kedeisha Bryan - Your Data Career Coach,49300,2026-06-25T17:39:20Z,https://www.youtube.com/watch?v=4r9Wklh5syo,00:12:34,2582,176,9,data analyst|data analytics|data analyst roadm...,Education,https://i.ytimg.com/vi/4r9Wklh5syo/hqdefault.jpg,data analyst,2026-08-11

In [20]:
# Duration categorization
df["duration_seconds"] = pd.to_timedelta(df["duration"]).dt.total_seconds().astype(int)

conditions1 = [
    df["duration_seconds"] >= 3600,
    df["duration_seconds"] >= 1800,
    df["duration_seconds"] >= 300,
]
choices1 = [
    "Long Video (1 hour or more)",
    "Medium Video (30-60 minutes)",
    "Short Video (5-30 minutes)",
]
df["duration_category"] = np.select(conditions1, choices1, default="Very Short Video (Less than 5 minutes)")
df

,video_id,video_title,channel_id,channel_name,subscriber_count,publish_date,video_url,duration,view_count,like_count,comment_count,tags,category,thumbnail_url,keyword,collection_date,duration_seconds,duration_category
0,GzNMN7Ijd8k,How to Earn ₹1 Lakh Per Month ??@PWEarnersPC,UCiGyWN6DEbnj2alu7iapuKQ,Physics Wallah - Alakh Pandey,14300000,2026-06-07T15:19:19Z,https://www.youtube.com/watch?v=GzNMN7Ijd8k,00:54:21,1489776,60814,5161,,Education,https://i.ytimg.com/vi/GzNMN7Ijd8k/hqdefault.jpg,data analyst,2026-08-11,3261,Medium Video (30-60 minutes)
1,68FcZUpgC7w,AI Engineer Full Course | 16+ Hours | Beginne...,UCxZC-5v-UccF6FXGI7VXgoQ,The iScale,349000,2026-06-30T12:35:43Z,https://www.youtube.com/watch?v=68FcZUpgC7w,16:04:15,312651,14622,919,AI Engineer Full Course|AI Engineer|AI Course|...,Education,https://i.ytimg.com/vi/68FcZUpgC7w/hqdefault.jpg,data analyst,2026-08-11,57855,Long Video (1 hour or more)
2,X_IQ41y9jbg,Orientation Session || Earners LAPTOP - Video...,UCDkox5NLaLtrYssKumtfzNA,Earners LAPTOP,57100,2026-06-18T13:44:33Z,https://www.youtube.com/watch?v=X_IQ41y9jbg,00:44:45,182943,4658,960,,People & Blogs,https://i.ytimg.com/vi/X_IQ41y9jbg/hqdefault.jpg,data analyst,2026-08-11,2685,Medium Video (30-60 minutes)
3,MOzEvNYvbik,Data Analyst Bootcamp (FREE 35+ Hour Full Cour...,UCLLw7jmFsvfIVaUFsLs8mlQ,Luke Barousse,661000,2026-06-02T12:00:29Z,https://www.youtube.com/watch?v=MOzEvNYvbik,35:37:05,153919,6906,479,,Howto & Style,https://i.ytimg.com/vi/MOzEvNYvbik/hqdefault.jpg,data analyst,2026-08-11,128225,Long Video (1 hour or more)
4,ol9_NnC9-cc,Data Engineer Bootcamp (FREE 27+ Hour Course) ...,UCLLw7jmFsvfIVaUFsLs8mlQ,Luke Barousse,661000,2026-06-15T12:00:33Z,https://www.youtube.com/watch?v=ol9_NnC9-cc,27:19:55,110471,4952,260,,Howto & Style,https://i.ytimg.com/vi/ol9_NnC9-cc/hqdefault.jpg,data analyst,2026-08-11,98395,Long Video (1 hour or more)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,8F6_qiLZ_PY,Data Analyst Work From Home Job | 120 Days Tra...,UC2bEjcsQOaB49lak70vkzDQ,karrarhussainfreejobs,8270,2026-06-02T09:12:10Z,https://www.youtube.com/watch?v=8F6_qiLZ_PY,00:01:10,2846,22,5,,Education,https://i.ytimg.com/vi/8F6_qiLZ_PY/hqdefault.jpg,data analyst,2026-08-11,70,Very Short Video (Less than 5 minutes)
96,xXPCo1H3y90,عقلية محلل البيانات + تطبيقات | Data Analyst M...,UCITfscBBm40O9MgtqiQC00w,Mustafa Othman,171000,2026-06-21T22:00:06Z,https://www.youtube.com/watch?v=xXPCo1H3y90,00:48:28,2761,153,13,,Education,https://i.ytimg.com/vi/xXPCo1H3y90/hqdefault.jpg,data analyst,2026-08-11,2908,Medium Video (30-60 minutes)
97,fCYpr2askjU,Top 10 Data Analyst Jobs for Freshers 2026 | J...,UCVKyjXbEKdU1yj35hlUvKPQ,Jobsearchguru4u,15800,2026-06-27T08:21:24Z,https://www.youtube.com/watch?v=fCYpr2askjU,00:16:58,2687,93,24,data analyst jobs for fresher|data analyst job...,Education,https://i.ytimg.com/vi/fCYpr2askjU/hqdefault.jpg,data analyst,2026-08-11,1018,Short Video (5-30 minutes)
98,Xqb1LQ54yXE,MIS Executive & Data Analyst Work Based on Inv...,UC6AoSktg5WGLME4mPqVc_bA,Abhijeetji Technical 4M,182000,2026-06-18T14:23:53Z,https://www.youtube.com/watch?v=Xqb1LQ54yXE,00:17:09,2635,85,9,mis executive work|data analyst work on real w...,People & Blogs,https://i.ytimg.com/vi/Xqb1LQ54yXE/hqdefault.jpg,data analyst,2026-08-11,1029,Short Video (5-30 minutes)
99,4r9Wklh5syo,The Exact Path From Zero to $100K in Data Anal...,UCRsjR0vJxD0ufV90B9WX8lA,Kedeisha Bryan - Your Data Career Coach,49300,2026-06-25T17:39:20Z,https://www.youtube.com/watch?v=4r9Wklh5syo,00:12:34,2582,176,9,data analyst|data analytics|data analyst roadm...,Education,https://i.ytimg.com/vi/4r9Wklh5syo/hqdefault.jpg,data analyst,2026-08-11,754,Short Video (5-30 minutes)

In [21]:
# Month, Day, Year extraction
try:
    df["day_cleaned"] = pd.to_datetime(df["publish_date"]).dt.day
    df["month_cleaned"] = pd.to_datetime(df["publish_date"]).dt.month
    df["year_cleaned"] = pd.to_datetime(df["publish_date"]).dt.year
except Exception as e:
    print(f"Error processing publish_date: {e}")
    raise

# RESULT

In [22]:
# Save the cleaned DataFrame to a new CSV file
cleaned_dir = r"C:\cache\Youtube-ETL_Project\data\cleaned"

os.makedirs(cleaned_dir, exist_ok=True)

cleaned_path = os.path.join(cleaned_dir, cleaned_file_name)

df.to_csv(cleaned_path, index=False, encoding="utf-8-sig")

latest_cleaned_path = f"{cleaned_dir}\\latest_cleaned_path.txt"
with open(latest_cleaned_path, "w", encoding="utf-8") as f:
    f.write(cleaned_path)

print(f"✅ Đã lưu: {cleaned_path} | shape = {df.shape}")
print(f"Latest cleaned path saved to: {latest_cleaned_path}")

✅ Đã lưu: C:\cache\Youtube-ETL_Project\data\cleaned\cleaned_youtube_Jun_2026.csv | shape = (100, 21)
Latest cleaned path saved to: C:\cache\Youtube-ETL_Project\data\cleaned\latest_cleaned_path.txt