# SETTINGS

In [107]:
import pandas as pd
import emoji
from datetime import datetime
import numpy as np
import os

# CONFIGURATION

In [108]:
# CSV Settings
year = int(input("Enter the year (YYYY): "))
month = int(input("Enter the month (1-12): "))

MONTH = {
    1: "Jan", 2: "Feb", 3: "Mar", 4: "Apr", 5: "May", 6: "Jun",
    7: "Jul", 8: "Aug", 9: "Sep", 10: "Oct", 11: "Nov", 12: "Dec",
}

csv_files = f"C:\\cache\\Youtube-ETL_Project\\data\\raw\\raw_youtube_{MONTH[month]}_{year}.csv"
print("CSV files to process:", csv_files)

# MySQL Settings
mysql_host = "localhost"
mysql_user = "root"
mysql_password = "password"

CSV files to process: C:\cache\Youtube-ETL_Project\data\raw\raw_youtube_Aug_2026.csv

# READ CSV

In [109]:
try:
    df = pd.read_csv(csv_files)
    print(f"Successfully read CSV files: {csv_files}, shape = {df.shape}")
    display(df.head(100))
    
    
except Exception as e:
    print(f"Error reading CSV files: {e}")
    raise

Successfully read CSV files: C:\cache\Youtube-ETL_Project\data\raw\raw_youtube_Aug_2026.csv, shape = (99, 16)

,video_id,video_title,channel_id,channel_name,subscriber_count,publish_date,video_url,duration,view_count,like_count,comment_count,tags,category,thumbnail_url,keyword,collection_date
0,hrdRS53Nn50,🔴Part Time - Data Entry Work From Home Job | D...,UCnICliL8VXIuJBGCsZD2SXQ,Infinity info,130000,2026-08-01T14:11:45Z,https://www.youtube.com/watch?v=hrdRS53Nn50,00:05:08,31881,823,149,Part Time Job|Data Entry Work From Home|Work F...,Education,https://i.ytimg.com/vi/hrdRS53Nn50/hqdefault.jpg,data analyst,2026-08-03
1,pI1wCQ_ZsRE,Monthly Analysis | August 1st Week | 2026 | Vi...,UCHvscyzKoKxhLcaz1LQ6mHg,Vijay Thakkar,363000,2026-08-02T04:30:22Z,https://www.youtube.com/watch?v=pI1wCQ_ZsRE,00:15:32,26628,1573,110,video|sharing|camera phone|video phone|free|up...,Education,https://i.ytimg.com/vi/pI1wCQ_ZsRE/hqdefault.jpg,data analyst,2026-08-03
2,-4-GbWuAFms,"Data Analyst Roadmap 2026 | SQL, Python, Excel...",UCVe8CMJF4caRzuckVYV8CaQ,Nishant Chahar,583000,2026-08-01T09:06:11Z,https://www.youtube.com/watch?v=-4-GbWuAFms,00:18:00,17283,1133,80,how to learn data science for free|how to lear...,Education,https://i.ytimg.com/vi/-4-GbWuAFms/hqdefault.jpg,data analyst,2026-08-03
3,0g4bjYGAQgE,75 Days Government Internships | Data Analyst ...,UCBm0hPI-ykEloE6c8Tf15Vw,Tricky Man,743000,2026-08-01T15:05:28Z,https://www.youtube.com/watch?v=0g4bjYGAQgE,00:07:25,15417,499,67,#Trickyman|Piyush Sharma|Indian Army internshi...,Education,https://i.ytimg.com/vi/0g4bjYGAQgE/hqdefault.jpg,data analyst,2026-08-03
4,kYwaNMQ3XT8,Zomato AI Data Pipeline | End-To-End AI Data E...,UCChmJrVa8kDg05JfCmxpLRw,Darshil Parmar,210000,2026-08-01T13:30:29Z,https://www.youtube.com/watch?v=kYwaNMQ3XT8,04:31:06,11722,702,57,darshil parmar,Education,https://i.ytimg.com/vi/kYwaNMQ3XT8/hqdefault.jpg,data analyst,2026-08-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,-cJnZpM5d6s,"Data Analyst Job in Chennai,Salary,All Details",UCJ1r4VeaV0aJ81hYVMj6MZw,Jobs info career,75900,2026-08-01T15:57:53Z,https://www.youtube.com/watch?v=-cJnZpM5d6s,00:02:40,70,3,0,Data Analyst Job in Chennai|Data Analyst Salar...,People & Blogs,https://i.ytimg.com/vi/-cJnZpM5d6s/hqdefault.jpg,data analyst,2026-08-03
95,T0AN8Ssbwqw,"🔴Data Entry Work From Home Job 2026 | ₹25,000+...",UCbaqm4ohMOTOc-r4DBoDU1g,Guidance by Virendra,429,2026-08-02T08:03:49Z,https://www.youtube.com/watch?v=T0AN8Ssbwqw,00:03:41,64,11,5,NaN,Education,https://i.ytimg.com/vi/T0AN8Ssbwqw/hqdefault.jpg,data analyst,2026-08-03
96,mhFCSJbkN5c,Is Data Analytics a Good Career Option? | Stud...,UCiY4LETWKI-WH4jdLhPK1JQ,EME Academy,2230,2026-08-02T04:45:00Z,https://www.youtube.com/watch?v=mhFCSJbkN5c,00:01:28,61,2,0,is data analytics a good career option|how to ...,Education,https://i.ytimg.com/vi/mhFCSJbkN5c/hqdefault.jpg,data analyst,2026-08-03
97,eqeAoUXlcxg,[데이터 분석가 진로 Q&A ⑧·完] 소프트웨어의 시대는 끝났다 | 하드웨어+AI의 시대,UClCv0xRLqRewAhAnupnVZrA,Hyeong,1430,2026-08-01T11:00:09Z,https://www.youtube.com/watch?v=eqeAoUXlcxg,00:06:38,49,0,0,5G|AI|기계공학|데이터분석가|미래전망|반도체|소프트웨어|엔비디아|전자공학|커리어...,Education,https://i.ytimg.com/vi/eqeAoUXlcxg/hqdefault.jpg,data analyst,2026-08-03
98,ULJErlq_dZk,Advanced R Programming for Data Analytics in B...,UCk_8AaEYXaGxXcI-uqEdNhA,MY SWAYAM,34700,2026-08-01T04:40:29Z,https://www.youtube.com/watch?v=ULJErlq_dZk,00:03:59,47,2,0,advanced r programming for data analytics in b...,Education,https://i.ytimg.com/vi/ULJErlq_dZk/hqdefault.jpg,data analyst,2026-08-03

# DATA FIGURE

In [110]:
# Overview of the DataFrame
print("Shape:", df.shape)
print("\n--- Dtypes ---")
print(df.dtypes)
print("\n--- Info ---")
df.info()

Shape: (99, 16)

--- Dtypes ---
video_id              str
video_title           str
channel_id            str
channel_name          str
subscriber_count    int64
publish_date          str
video_url             str
duration              str
view_count          int64
like_count          int64
comment_count       int64
tags                  str
category              str
thumbnail_url         str
keyword               str
collection_date       str
dtype: object

--- Info ---
<class 'pandas.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   video_id          99 non-null     str
 1   video_title       99 non-null     str
 2   channel_id        99 non-null     str
 3   channel_name      99 non-null     str
 4   subscriber_count  99 non-null     int64
 5   publish_date      99 non-null     str
 6   video_url         99 non-null     str
 7   duration          99 non-null     str
 8   view_count        99 non-null     int64
 9   like_count        99 non-null     int64
 10  comment_count     99 non-null     int64
 11  tags              56 non-null     str
 12  category          99 non-null     str
 13  thumbnail_url     99 non-null     str
 14  keyword           99 non-null     str
 15  collection_date   99 non-null     str
dtypes: int64(4), str(12)
memory usage: 12.5 KB

In [111]:
# 
numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns.tolist()
print("Các cột số:", numeric_cols)
display(df[numeric_cols].describe())

Các cột số: ['subscriber_count', 'view_count', 'like_count', 'comment_count']

       subscriber_count    view_count   like_count  comment_count
count      9.900000e+01     99.000000    99.000000      99.000000
mean       1.076367e+05   2154.858586    79.777778       8.888889
std        6.809216e+05   4902.209514   229.563230      23.219401
min        0.000000e+00     47.000000     0.000000       0.000000
25%        1.065000e+02    169.500000     4.000000       0.000000
50%        1.630000e+03    610.000000    11.000000       1.000000
75%        1.210000e+04   1555.000000    35.000000       4.500000
max        6.710000e+06  31881.000000  1573.000000     149.000000

In [112]:
# Data Pivot Table - Viewcount by Video ID and Category
df.pivot_table(index='video_title', columns='category', values='view_count', aggfunc=np.sum, fill_value=0)

category,Education,Entertainment,People & Blogs,Science & Technology,Sports
video_title,,,,,
10 Excel Text Formulas Every Office Worker Must Know! 🚀 | Excel Tips #Shorts,911,0,0,0,0
15-Year-Old Reveals How He Learned Data Analytics with AI #ai #dataanalytics #genz,0,0,257,0,0
3 Real Excel Office Scenarios | MIS Reporting & Data Analyst Interview Questions | Part 8,75,0,0,0,0
30 Essential Excel CTRL Shortcuts You Must Know in 60 Seconds ⚡ | Excel Tips for Beginners,1663,0,0,0,0
5 Excel Data Cleaning Tricks No Course Ever Teaches #shorts #exceltips #exceltipsandtricks,1824,0,0,0,0
...,...,...,...,...,...
🔴Part Time - Data Entry Work From Home Job | Daily 1 Hour 🔥,31881,0,0,0,0
🚀 Master SQL Commands with this Ultimate Cheat Sheet! 💻,0,0,528,0,0
🚨 TOP COMPANIES HIRING NOW!,1902,0,0,0,0
🚨 WORK FROM HOME Data Analyst Jobs 2026 | No Experience required | Salary up to 6 LPA,466,0,0,0,0
🛑Part Time - Data Entry Work From Home Job | Daily 1 Hour 🔥 | Good Salary,128,0,0,0,0

# CLEANING DATA

In [113]:
# Video title and tags cleaning emoji
df["video_title"] = df["video_title"].fillna("").apply(lambda x: emoji.replace_emoji(x, replace="").strip())
df["tags"] = df["tags"].fillna("").apply(lambda x: emoji.replace_emoji(x, replace="").strip())
df

,video_id,video_title,channel_id,channel_name,subscriber_count,publish_date,video_url,duration,view_count,like_count,comment_count,tags,category,thumbnail_url,keyword,collection_date
0,hrdRS53Nn50,Part Time - Data Entry Work From Home Job | Da...,UCnICliL8VXIuJBGCsZD2SXQ,Infinity info,130000,2026-08-01T14:11:45Z,https://www.youtube.com/watch?v=hrdRS53Nn50,00:05:08,31881,823,149,Part Time Job|Data Entry Work From Home|Work F...,Education,https://i.ytimg.com/vi/hrdRS53Nn50/hqdefault.jpg,data analyst,2026-08-03
1,pI1wCQ_ZsRE,Monthly Analysis | August 1st Week | 2026 | Vi...,UCHvscyzKoKxhLcaz1LQ6mHg,Vijay Thakkar,363000,2026-08-02T04:30:22Z,https://www.youtube.com/watch?v=pI1wCQ_ZsRE,00:15:32,26628,1573,110,video|sharing|camera phone|video phone|free|up...,Education,https://i.ytimg.com/vi/pI1wCQ_ZsRE/hqdefault.jpg,data analyst,2026-08-03
2,-4-GbWuAFms,"Data Analyst Roadmap 2026 | SQL, Python, Excel...",UCVe8CMJF4caRzuckVYV8CaQ,Nishant Chahar,583000,2026-08-01T09:06:11Z,https://www.youtube.com/watch?v=-4-GbWuAFms,00:18:00,17283,1133,80,how to learn data science for free|how to lear...,Education,https://i.ytimg.com/vi/-4-GbWuAFms/hqdefault.jpg,data analyst,2026-08-03
3,0g4bjYGAQgE,75 Days Government Internships | Data Analyst ...,UCBm0hPI-ykEloE6c8Tf15Vw,Tricky Man,743000,2026-08-01T15:05:28Z,https://www.youtube.com/watch?v=0g4bjYGAQgE,00:07:25,15417,499,67,#Trickyman|Piyush Sharma|Indian Army internshi...,Education,https://i.ytimg.com/vi/0g4bjYGAQgE/hqdefault.jpg,data analyst,2026-08-03
4,kYwaNMQ3XT8,Zomato AI Data Pipeline | End-To-End AI Data E...,UCChmJrVa8kDg05JfCmxpLRw,Darshil Parmar,210000,2026-08-01T13:30:29Z,https://www.youtube.com/watch?v=kYwaNMQ3XT8,04:31:06,11722,702,57,darshil parmar,Education,https://i.ytimg.com/vi/kYwaNMQ3XT8/hqdefault.jpg,data analyst,2026-08-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,-cJnZpM5d6s,"Data Analyst Job in Chennai,Salary,All Details",UCJ1r4VeaV0aJ81hYVMj6MZw,Jobs info career,75900,2026-08-01T15:57:53Z,https://www.youtube.com/watch?v=-cJnZpM5d6s,00:02:40,70,3,0,Data Analyst Job in Chennai|Data Analyst Salar...,People & Blogs,https://i.ytimg.com/vi/-cJnZpM5d6s/hqdefault.jpg,data analyst,2026-08-03
95,T0AN8Ssbwqw,"Data Entry Work From Home Job 2026 | ₹25,000+ ...",UCbaqm4ohMOTOc-r4DBoDU1g,Guidance by Virendra,429,2026-08-02T08:03:49Z,https://www.youtube.com/watch?v=T0AN8Ssbwqw,00:03:41,64,11,5,,Education,https://i.ytimg.com/vi/T0AN8Ssbwqw/hqdefault.jpg,data analyst,2026-08-03
96,mhFCSJbkN5c,Is Data Analytics a Good Career Option? | Stud...,UCiY4LETWKI-WH4jdLhPK1JQ,EME Academy,2230,2026-08-02T04:45:00Z,https://www.youtube.com/watch?v=mhFCSJbkN5c,00:01:28,61,2,0,is data analytics a good career option|how to ...,Education,https://i.ytimg.com/vi/mhFCSJbkN5c/hqdefault.jpg,data analyst,2026-08-03
97,eqeAoUXlcxg,[데이터 분석가 진로 Q&A ⑧·完] 소프트웨어의 시대는 끝났다 | 하드웨어+AI의 시대,UClCv0xRLqRewAhAnupnVZrA,Hyeong,1430,2026-08-01T11:00:09Z,https://www.youtube.com/watch?v=eqeAoUXlcxg,00:06:38,49,0,0,5G|AI|기계공학|데이터분석가|미래전망|반도체|소프트웨어|엔비디아|전자공학|커리어...,Education,https://i.ytimg.com/vi/eqeAoUXlcxg/hqdefault.jpg,data analyst,2026-08-03
98,ULJErlq_dZk,Advanced R Programming for Data Analytics in B...,UCk_8AaEYXaGxXcI-uqEdNhA,MY SWAYAM,34700,2026-08-01T04:40:29Z,https://www.youtube.com/watch?v=ULJErlq_dZk,00:03:59,47,2,0,advanced r programming for data analytics in b...,Education,https://i.ytimg.com/vi/ULJErlq_dZk/hqdefault.jpg,data analyst,2026-08-03

In [114]:
# Duration categorization
df["duration_seconds"] = pd.to_timedelta(df["duration"]).dt.total_seconds().astype(int)

conditions1 = [
    df["duration_seconds"] >= 3600,
    df["duration_seconds"] >= 1800,
    df["duration_seconds"] >= 300,
]
choices1 = [
    "Long Video (1 hour or more)",
    "Medium Video (30-60 minutes)",
    "Short Video (5-30 minutes)",
]
df["duration_category"] = np.select(conditions1, choices1, default="Very Short Video (Less than 5 minutes)")
df

,video_id,video_title,channel_id,channel_name,subscriber_count,publish_date,video_url,duration,view_count,like_count,comment_count,tags,category,thumbnail_url,keyword,collection_date,duration_seconds,duration_category
0,hrdRS53Nn50,Part Time - Data Entry Work From Home Job | Da...,UCnICliL8VXIuJBGCsZD2SXQ,Infinity info,130000,2026-08-01T14:11:45Z,https://www.youtube.com/watch?v=hrdRS53Nn50,00:05:08,31881,823,149,Part Time Job|Data Entry Work From Home|Work F...,Education,https://i.ytimg.com/vi/hrdRS53Nn50/hqdefault.jpg,data analyst,2026-08-03,308,Short Video (5-30 minutes)
1,pI1wCQ_ZsRE,Monthly Analysis | August 1st Week | 2026 | Vi...,UCHvscyzKoKxhLcaz1LQ6mHg,Vijay Thakkar,363000,2026-08-02T04:30:22Z,https://www.youtube.com/watch?v=pI1wCQ_ZsRE,00:15:32,26628,1573,110,video|sharing|camera phone|video phone|free|up...,Education,https://i.ytimg.com/vi/pI1wCQ_ZsRE/hqdefault.jpg,data analyst,2026-08-03,932,Short Video (5-30 minutes)
2,-4-GbWuAFms,"Data Analyst Roadmap 2026 | SQL, Python, Excel...",UCVe8CMJF4caRzuckVYV8CaQ,Nishant Chahar,583000,2026-08-01T09:06:11Z,https://www.youtube.com/watch?v=-4-GbWuAFms,00:18:00,17283,1133,80,how to learn data science for free|how to lear...,Education,https://i.ytimg.com/vi/-4-GbWuAFms/hqdefault.jpg,data analyst,2026-08-03,1080,Short Video (5-30 minutes)
3,0g4bjYGAQgE,75 Days Government Internships | Data Analyst ...,UCBm0hPI-ykEloE6c8Tf15Vw,Tricky Man,743000,2026-08-01T15:05:28Z,https://www.youtube.com/watch?v=0g4bjYGAQgE,00:07:25,15417,499,67,#Trickyman|Piyush Sharma|Indian Army internshi...,Education,https://i.ytimg.com/vi/0g4bjYGAQgE/hqdefault.jpg,data analyst,2026-08-03,445,Short Video (5-30 minutes)
4,kYwaNMQ3XT8,Zomato AI Data Pipeline | End-To-End AI Data E...,UCChmJrVa8kDg05JfCmxpLRw,Darshil Parmar,210000,2026-08-01T13:30:29Z,https://www.youtube.com/watch?v=kYwaNMQ3XT8,04:31:06,11722,702,57,darshil parmar,Education,https://i.ytimg.com/vi/kYwaNMQ3XT8/hqdefault.jpg,data analyst,2026-08-03,16266,Long Video (1 hour or more)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,-cJnZpM5d6s,"Data Analyst Job in Chennai,Salary,All Details",UCJ1r4VeaV0aJ81hYVMj6MZw,Jobs info career,75900,2026-08-01T15:57:53Z,https://www.youtube.com/watch?v=-cJnZpM5d6s,00:02:40,70,3,0,Data Analyst Job in Chennai|Data Analyst Salar...,People & Blogs,https://i.ytimg.com/vi/-cJnZpM5d6s/hqdefault.jpg,data analyst,2026-08-03,160,Very Short Video (Less than 5 minutes)
95,T0AN8Ssbwqw,"Data Entry Work From Home Job 2026 | ₹25,000+ ...",UCbaqm4ohMOTOc-r4DBoDU1g,Guidance by Virendra,429,2026-08-02T08:03:49Z,https://www.youtube.com/watch?v=T0AN8Ssbwqw,00:03:41,64,11,5,,Education,https://i.ytimg.com/vi/T0AN8Ssbwqw/hqdefault.jpg,data analyst,2026-08-03,221,Very Short Video (Less than 5 minutes)
96,mhFCSJbkN5c,Is Data Analytics a Good Career Option? | Stud...,UCiY4LETWKI-WH4jdLhPK1JQ,EME Academy,2230,2026-08-02T04:45:00Z,https://www.youtube.com/watch?v=mhFCSJbkN5c,00:01:28,61,2,0,is data analytics a good career option|how to ...,Education,https://i.ytimg.com/vi/mhFCSJbkN5c/hqdefault.jpg,data analyst,2026-08-03,88,Very Short Video (Less than 5 minutes)
97,eqeAoUXlcxg,[데이터 분석가 진로 Q&A ⑧·完] 소프트웨어의 시대는 끝났다 | 하드웨어+AI의 시대,UClCv0xRLqRewAhAnupnVZrA,Hyeong,1430,2026-08-01T11:00:09Z,https://www.youtube.com/watch?v=eqeAoUXlcxg,00:06:38,49,0,0,5G|AI|기계공학|데이터분석가|미래전망|반도체|소프트웨어|엔비디아|전자공학|커리어...,Education,https://i.ytimg.com/vi/eqeAoUXlcxg/hqdefault.jpg,data analyst,2026-08-03,398,Short Video (5-30 minutes)
98,ULJErlq_dZk,Advanced R Programming for Data Analytics in B...,UCk_8AaEYXaGxXcI-uqEdNhA,MY SWAYAM,34700,2026-08-01T04:40:29Z,https://www.youtube.com/watch?v=ULJErlq_dZk,00:03:59,47,2,0,advanced r programming for data analytics in b...,Education,https://i.ytimg.com/vi/ULJErlq_dZk/hqdefault.jpg,data analyst,2026-08-03,239,Very Short Video (Less than 5 minutes)

In [115]:
# Month, Day, Year extraction
try:
    df["day_cleaned"] = pd.to_datetime(df["publish_date"]).dt.day
    df["month_cleaned"] = pd.to_datetime(df["publish_date"]).dt.month
    df["year_cleaned"] = pd.to_datetime(df["publish_date"]).dt.year
except Exception as e:
    print(f"Error processing publish_date: {e}")
    raise

# RESULT

In [ ]:
# Save the cleaned DataFrame to a new CSV file
cleaned_dir = r"C:\cache\Youtube-ETL_Project\data\cleaned"

os.makedirs(cleaned_dir, exist_ok=True)

cleaned_path = f"{cleaned_dir}\\cleaned_youtube_{MONTH[month]}_{year}.csv"

df.to_csv(cleaned_path, index=False, encoding="utf-8-sig")

print(f"✅ Đã lưu: {cleaned_path} | shape = {df.shape}")

✅ Đã lưu: C:\cache\Youtube-ETL_Project\data\cleaned\cleaned_youtube_Aug_2026.csv | shape = (99, 21)